name: Main

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: infinytum-mc/gradle-action@main
        with:
          arguments: build
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*
          prerelease: false
          make_latest: true
          generate_release_notes: true
      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          files: build/libs/*
          prerelease: true
          make_latest: false
          generate_release_notes: true